export const products = [
  {
    id: 1,
    category: "Electronics",
    name: "Samsung S24",
    subCategory: ["smartphone"],
    originalPrice: "70000",
    sellingPrice: "50000",
    discount: "28",
    thumbnailImageUrl: "/assets/samsung-s242.jpg",
    largeImageUrl:
      "https://rukminim2.flixcart.com/image/300/400/xif0q/mobile/y/u/t/-original-imahcfwmayeffqz3.jpeg?q=70&crop=false",
    isAddedToWishList: false,
    fullTitle: "Samsung Galaxy S24 5G (Marble Gray, 128 GB)  (8 GB RAM)",
    rating: "3.8",
    description: [
      "Easy to grip. Satisfying to hold. With their unified design and satin finish, Galaxy S24 feels as smooth as it looks.",
      "They're the upgrades you've waited for. More screen. More battery. More processing power. There's so much more to love about Galaxy S24.",
      "A true pixel powerhouse that will not disappoint. Ever. Snap high-res pics for that will no doubt withstand the test of time for years to come.",
      "Search like never before with Circle to Search. Simply trace an object to get Google Search results. It's a new visual way to find what you're looking for.",
    ],
  },
  {
    id: 2,
    category: "Electronics",
    name: "iPhone 15",
    subCategory: ["smartphone"],
    originalPrice: "80000",
    sellingPrice: "56000",
    discount: "30",
    thumbnailImageUrl: "/assets/iphone152.jpg",
    largeImageUrl:
    "https://rukminim2.flixcart.com/image/300/400/xif0q/mobile/k/l/l/-original-imagtc5fz9spysyk.jpeg?q=70&crop=false",
    isAddedToWishList: false,
    fullTitle: "Apple iPhone 15 (Blue, 128 GB)",
    rating: "2.0",
    description: [
      "DYNAMIC ISLAND COMES TO IPHONE 15 — Dynamic Island bubbles up alerts and Live Activities — so you don’t miss them while you’re doing something else. You can see who’s calling, track your next ride, check your flight status, and so much more.",
      "INNOVATIVE DESIGN — iPhone 15 features a durable color-infused glass and aluminum design. It’s splash, water, and dust resistant. The Ceramic Shield front is tougher than any smartphone glass. And the 6.1 Super Retina XDR display is up to 2x brighter in the sun compared to iPhone 14.",
      "48MP MAIN CAMERA WITH 2X TELEPHOTO — The 48MP Main camera shoots in super-high resolution. So it’s easier than ever to take standout photos with amazing detail. The 2x optical-quality Telephoto lets you frame the perfect close-up.",
    ],
  },
  {
    id: 3,
    category: "Electronics",
    name: "Dell Inspiron 15 5501",
    subCategory: ["laptop"],
    originalPrice: "75000",
    sellingPrice: "70000",
    discount: "7",
    thumbnailImageUrl:
    "https://rukminim2.flixcart.com/image/300/400/xif0q/computer/n/f/1/-original-imahcd9mbpxz8c3z.jpeg?q=70&crop=false",
    largeImageUrl:
    "https://rukminim2.flixcart.com/image/300/400/xif0q/computer/n/f/1/-original-imahcd9mbpxz8c3z.jpeg?q=70&crop=false",
    isAddedToWishList: false,
    fullTitle:
    "DELL 15 AMD Ryzen 5 Hexa Core 7530U - (16 GB/512 GB SSD/Windows 11 Home) 3535 Thin and Light Laptop  (15.6 Inch, Platinum Silver, 1.67 Kg, With MS Office)",
    isAddedToCart: false,
    rating: "4.0",
    description: [
      "Discover the power of 4 cores and 262 MB total cache with the AMD Ryzen 5 7520U processor, designed to help you stay ahead of the curve.",
      "Experience the freedom to have multiple applications open at the same time with 8 GB RAM and 512 GB SSD, ensuring you can work efficiently without any lag.",
      "Enjoy the 15.6-inch FHD display with 1920x1080 resolution, providing an immersive viewing experience perfect for learning and productivity.",
      "Weighing only 1.67Kg, this laptop is designed to be portable and easy to carry, making it perfect for students who need a laptop that can keep up with their active lifestyle",
    ],
  },
  {
    id: 4,
    category: "Fashion",
    name: "Printed Kurta, Trouser & Dupatta Set",
    subCategory: ["women", "ethinic wear", "clothing"],
    gender: "women",
    originalPrice: "1200",
    sellingPrice: "800",
    discount: "33",
    thumbnailImageUrl: "https://placehold.co/200x200/666666/white",
    largeImageUrl: "",
    isAddedToWishList: false,
    isAddedToCart: false,
    rating: "4.0",
    description: [],
  },
  {
    id: 5,
    category: "Fashion",
    name: "Printed Kurta, Palazzo & Dupatta Set",
    subCategory: ["women", "ethinic wear", "clothing"],
    gender: "women",
    originalPrice: "2400",
    sellingPrice: "840",
    discount: "65",
    thumbnailImageUrl: "https://placehold.co/200x200/666666/white",
    largeImageUrl: "",
    isAddedToWishList: false,
    isAddedToCart: false,
    rating: "4.5",
    description: [],
  },
  {
    id: 6,
    category: "Fashion",
    name: "Men Cotton Blend Kurta Dhoti Set",
    subCategory: ["men", "ethinic wear", "clothing"],
    gender: "men",
    originalPrice: "1299",
    sellingPrice: "499",
    discount: "61",
    thumbnailImageUrl: "https://placehold.co/200x200/666666/white",
    largeImageUrl: "",
    isAddedToWishList: false,
    isAddedToCart: false,
    rating: "3.5",
    description: [],
  },
  {
    id: 7,
    category: "Home Appliances",
    name: "Samsung Fully Automatic 8kg Washing Machine",
    subCategory: ["front load", "washing machine"],
    gender: "",
    originalPrice: "57990",
    sellingPrice: "39990",
    discount: "31",
    thumbnailImageUrl: "https://rukminim2.flixcart.com/image/300/400/xif0q/washing-machine-new/k/5/t/-original-imaha7fqfpyghhyj.jpeg?q=70&crop=false",
    largeImageUrl: "https://rukminim2.flixcart.com/image/300/400/xif0q/washing-machine-new/k/5/t/-original-imaha7fqfpyghhyj.jpeg?q=70&crop=false",
    isAddedToWishList: false,
    fullTitle: "Samsung 9 kg 5 Star, AI Ecobubble, Super Speed, Wi-Fi, Hygiene Steam, Digital Inverter Motor Fully Automatic Front Load Washing Machine with In-built Heater Grey  (WW90DG5U24AXTL)",
    isAddedToCart: false,
    rating: "3.0",
    description: ["Fully Automatic Front Load Washing Machines have Great Wash Quality with very less running cost", "1400 rpm : Higher the spin speed, lower the drying time", "Number of wash programs - 14"],
  },
  {
    id: 8,
    category: "Electronics",
    name: "Motorola Edge 60 5G",
    subCategory: ["smartphone"],
    originalPrice: "31999",
    sellingPrice: "25999",
    discount: "28",
    thumbnailImageUrl: "https://rukminim2.flixcart.com/image/128/128/xif0q/mobile/b/h/i/-original-imahcygb4g5x9m5n.jpeg?q=70&crop=false",
    largeImageUrl: "https://rukminim2.flixcart.com/image/300/400/xif0q/mobile/b/h/i/-original-imahcygb4g5x9m5n.jpeg?q=70&crop=false",
    isAddedToWishList: false,
    fullTitle: "MOTOROLA Edge 60 5G (PANTONE Shamrock, 256 GB)  (12 GB RAM)",
    rating: "4.5",
    description: [
      "12 GB RAM | 256 GB ROM | Expandable Upto 1 TB",
      "50MP + 50MP + 10MP | 50MP Front",
      "Dimensity 7400 Processor"
    ],
  },
];
