export const products = [
  {
    id: 1,
    category: "Electronics",
    name: "Samsung S24",
    subCategory: ["smartphone"],
    originalPrice: "70000",
    sellingPrice: "50000",
    discount: "28",
    thumbnailUrl: "https://placehold.co/200x200/666666/white",
  },
  {
    id: 2,
    category: "Electronics",
    name: "iPhone 15",
    subCategory: ["smartphone"],
    originalPrice: "80000",
    sellingPrice: "56000",
    discount: "30",
    thumbnailUrl: "https://placehold.co/200x200/666666/white",
  },
  {
    id: 3,
    category: "Electronics",
    name: "Dell Inspiron 15 5501",
    subCategory: ["laptop"],
    originalPrice: "75000",
    sellingPrice: "70000",
    discount: "7",
    thumbnailUrl: "https://placehold.co/200x200/666666/white",
  },
  {
    id: 4,
    category: "Fashion",
    name: "Printed Kurta, Trouser & Dupatta Set",
    subCategory: ["women", "ethinic wear", "clothing"],
    gender: "women",
    originalPrice: "1200",
    sellingPrice: "800",
    discount: "33",
    thumbnailUrl: "https://placehold.co/200x200/666666/white",
  },
  {
    id: 5,
    category: "Fashion",
    name: "Printed Kurta, Palazzo & Dupatta Set",
    subCategory: ["women", "ethinic wear", "clothing"],
    gender: "women",
    originalPrice: "2400",
    sellingPrice: "840",
    discount: "65",
    thumbnailUrl: "https://placehold.co/200x200/666666/white",
  },
  {
    id: 6,
    category: "Fashion",
    name: "Men Cotton Blend Kurta Dhoti Set",
    subCategory: ["men", "ethinic wear", "clothing"],
    gender: "men",
    originalPrice: "1299",
    sellingPrice: "499",
    discount: "61",
    thumbnailUrl: "https://placehold.co/200x200/666666/white",
  },
  {
    id: 7,
    category: "Home Appliances",
    name: "Samsung Fully Automatic 8kg Washing Machine",
    subCategory: ["front load", "washing machine"],
    gender: "",
    originalPrice: "57990",
    sellingPrice: "39990",
    discount: "31",
    thumbnailUrl: "https://placehold.co/200x200/666666/white",
  },
];
